import { Inter } from 'next/font/google';
import './globals.css';
import SideNav from '@/components/SideNav';
import MarginWidthWrapper from '@/components/MarginWidthWrapper';
import PageWrapper from '@/components/PageWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SideNav />
        <MarginWidthWrapper>
          <PageWrapper>{children}</PageWrapper>
        </MarginWidthWrapper>
      </body>
    </html>
  );
}
